### ISSUE TITLE
Idempotency of DELETE

### ISSUE THREAD

**Issue by mevdschee** [LeaseWeb/api-standards#4]
Should we not declare DELETE to be idempotent? It can be executed multiple times without leading to a different result, only side effect is that you may return a success (200?) or failure (404?) response. Maybe we can make this a little clearer. Not only whether or not it is idempotent, but also why it is or why it is not.

**Comment by RolphH** [comment]
You are correct. DELETE is idempotent as the result on the server is the same at all times. The response code might differ, but that doesn't affect the idempotency.

**Comment by spoelwijk** [comment]
Thanks @mevdschee
