### ISSUE TITLE
Support for pre-flight (OPTIONS) requests and CORS headers

### ISSUE THREAD

**Issue by mevdschee** [LeaseWeb/api-standards#8]
Javascript widgets may run on various URLs and will require CORS (Cross-origin resource sharing) headers, see [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS?redirectlocale=en-US&redirectslug=HTTP_access_control). Libraries like AngularJS may use pre-flight (OPTIONS) requests to read these CORS headers. Should we support these?

**Comment by RolphH** [comment]
At this moment we don't support this on our authentication layer due to security risks. If really needed we can discuss.
