### ISSUE TITLE
Is search always substring?

### ISSUE THREAD

**Issue by mevdschee** [LeaseWeb/api-standards#9]
What if I want start-of-string or end-of-string? Should we support character and/or string wildcard characters? Glob for instance has "*" for string and "?" for character wildcards, while SQL has "%" and "_". This would be more expressive.

**Comment by mevdschee** [comment]
Also I did not understand the note 'search is not filtering'. What does that mean? Can it be explained?

**Comment by piannelli** [comment]
I actually was the one writing "Search is not filtering".

Searching can be a very complex operation and can take care of many things.
For instance, when searching items on a collection, you may return them with a specific order or even provide with the search results some specific metadata, such as the relevance score, ranking, etc to name some or order the results in a specific way.

Filtering, instead, is a very simple process where you go through what you already have and just remove records from it. You don't have complex algorithms to follow other than just the filtering criteria.

So, assuming the resource:

GET /v1/domains/leaseweb.com/dnsRecords?q=amsterdam

This may produce the following result:

[ "domain.amsterdam", "other.amsterdam", "a.amsterdam", "new-amsterdam.com", "amsterdam.com" ]

As you can see, the search is returning you first domains that have extension ".amsterdam" followed by any domain that has "amsterdam" in it. Additionally, is ordering these subsets by the length of their 2nd level domain.

you may then apply filtering to this result, saying for instance &active=1, that will lead in a result like:

[ "a.amsterdam", "new-amsterdam.com", "amsterdam.com" ]

Hope is clear.

And about filtering start/end of the string, any approach can be taken. I personally prefer only * to avoid url-encoding issues and keeping things simple for the user. But in general, I mostly relay on ElasticSearch, n-grams and relevance score for most of the text-based searches. For simple searches, like the dnsRecord example, I would just stick to * as it is good enough to provide results to the user that will be further narrowed down.

**Comment by mevdschee** [comment]
It is clear to me: Substring search it is, which is much more than just filtering :-)
